version: "3"
services:
  server:
    container_name: cpe-guesser
    image: cpe-guesser:1.2
    build: ..
    volumes:
      - ../data/:/data/:rw
      - ./settings.yaml:/app/config/settings.yaml
    ports:
      - 8000:8000
    depends_on:
      - valkey
  valkey:
    container_name: cpe-guesser-db
    image: "valkey/valkey:7.2.8"
    ports:
      - 6379:6379